export const cities = [
  { key: "1", value: "A Coruña" },
  { key: "2", value: "Aachen" },
  { key: "3", value: "Aarhus" },
  { key: "4", value: "Abbeville" },
  { key: "5", value: "Aberdeen (UK)" },
  { key: "6", value: "Aberdeen (South Dakota)" },
  { key: "7", value: "Aberdeen (Washington)" },
  { key: "8", value: "Abidjan" },
  { key: "9", value: "Abilene" },
  { key: "10", value: "Abu Dhabi" },
  { key: "11", value: "Abuja" },
  { key: "12", value: "Acapulco" },
  { key: "13", value: "Accra" },
  { key: "14", value: "Adamstown" },
  { key: "15", value: "Addis Ababa" },
  { key: "16", value: "Adelaide" },
  { key: "17", value: "Adelboden" },
  { key: "18", value: "Agadir" },
  { key: "19", value: "Agde" },
  { key: "20", value: "Agen" },
  { key: "21", value: "Agios Nikolaos" },
  { key: "22", value: "Agra" },
  { key: "23", value: "Agrigento" },
  { key: "24", value: "Agropoli" },
  { key: "25", value: "Ahmedabad" },
  { key: "26", value: "Aigues-Mortes" },
  { key: "27", value: "Aix-en-Provence" },
  { key: "28", value: "Aix-les-Bains" },
  { key: "29", value: "Ajaccio" },
  { key: "30", value: "Ajman" },
  { key: "31", value: "Akron" },
  { key: "32", value: "Al Ain" },
  { key: "33", value: "Alanya" },
  { key: "34", value: "Alaró" },
  { key: "35", value: "Albacete" },
  { key: "36", value: "Albany" },
  { key: "37", value: "Albenga" },
  { key: "38", value: "Albi" },
  { key: "39", value: "Albufeira" },
  { key: "40", value: "Albuquerque" },
  { key: "41", value: "Alcudia" },
  { key: "42", value: "Aleppo" },
  { key: "43", value: "Alessandria" },
  { key: "44", value: "Ålesund" },
  { key: "45", value: "Alexandria (U.S.)" },
  { key: "46", value: "Alexandria (Egypt)" },
  { key: "47", value: "Algeciras" },
  { key: "48", value: "Alghero" },
  { key: "49", value: "Algiers" },
  { key: "50", value: "Alicante" },
  { key: "51", value: "Alkmaar" },
  { key: "52", value: "Allentown" },
  { key: "53", value: "Almaty" },
  { key: "54", value: "Alofi" },
  { key: "55", value: "Alpe d'Huez" },
  { key: "56", value: "Alta Badia" },
  { key: "57", value: "Altea" },
  { key: "58", value: "Altoona" },
  { key: "59", value: "Amalfi" },
  { key: "60", value: "Amapala" },
  { key: "61", value: "Amarillo" },
  { key: "62", value: "Ambon" },
  { key: "63", value: "Amersfoort" },
  { key: "64", value: "Amiens" },
  { key: "65", value: "Amman" },
  { key: "66", value: "Amsterdam" },
  { key: "67", value: "Anaheim" },
  { key: "68", value: "Anchorage" },
  { key: "69", value: "Ancona" },
  { key: "70", value: "Andalo" },
  { key: "71", value: "Andermatt" },
  { key: "72", value: "Andorra la Vella" },
  { key: "73", value: "Andratx" },
  { key: "74", value: "Andria" },
  { key: "75", value: "Angeles City" },
  { key: "76", value: "Angers" },
  { key: "77", value: "Angoulême" },
  { key: "78", value: "Ankara" },
  { key: "79", value: "Ann Arbor" },
  { key: "80", value: "Annapolis" },
  { key: "81", value: "Annecy" },
  { key: "82", value: "Antalya" },
  { key: "83", value: "Antananarivo" },
  { key: "84", value: "Antibes" },
  { key: "85", value: "Antigua Guatemala" },
  { key: "86", value: "Antwerp" },
  { key: "87", value: "Anzio" },
  { key: "88", value: "Ao Nang" },
  { key: "89", value: "Aosta" },
  { key: "90", value: "Apeldoorn" },
  { key: "91", value: "Apia" },
  { key: "92", value: "Appleton" },
  { key: "93", value: "Aqaba" },
  { key: "94", value: "Aracaju" },
  { key: "95", value: "Arcachon" },
  { key: "96", value: "Arenzano" },
  { key: "97", value: "Arequipa" },
  { key: "98", value: "Arezzo" },
  { key: "99", value: "Argostoli" },
  { key: "100", value: "Arica" },
  { key: "101", value: "Arles" },
  { key: "102", value: "Arlington (Virginia)" },
  { key: "103", value: "Arlington (Texas)" },
  { key: "104", value: "Armagh" },
  { key: "105", value: "Arnhem" },
  { key: "106", value: "Arosa" },
  { key: "107", value: "Arras" },
  { key: "108", value: "Arrecife" },
  { key: "109", value: "Artà" },
  { key: "110", value: "Asbury Park" },
  { key: "111", value: "Ascoli Piceno" },
  { key: "112", value: "Ascona" },
  { key: "113", value: "Ashdod" },
  { key: "114", value: "Ashgabat" },
  { key: "115", value: "Ashkelon" },
  { key: "116", value: "Asmara" },
  { key: "117", value: "Aspen" },
  { key: "118", value: "Asti" },
  { key: "119", value: "Astoria" },
  { key: "120", value: "Asunción" },
  { key: "121", value: "Atafu" },
  { key: "122", value: "Athens" },
  { key: "123", value: "Athlone" },
  { key: "124", value: "Atlanta" },
  { key: "125", value: "Atlantic City" },
  { key: "126", value: "Auckland" },
  { key: "127", value: "Augsburg" },
  { key: "128", value: "Augusta (Georgia)" },
  { key: "129", value: "Augusta (Maine)" },
  { key: "130", value: "Aurora (Colorado)" },
  { key: "131", value: "Aurora (Illinois)" },
  { key: "132", value: "Austin" },
  { key: "133", value: "Auxerre" },
  { key: "134", value: "Avalon (California)" },
  { key: "135", value: "Avalon (New Jersey)" },
  { key: "136", value: "Avarua" },
  { key: "137", value: "Aveiro" },
  { key: "138", value: "Avellino" },
  { key: "139", value: "Avignon" },
  { key: "140", value: "Avila Beach" },
  { key: "141", value: "Avoriaz" },
  { key: "142", value: "Axamer Lizum" },
  { key: "143", value: "Ayia Napa" },
  { key: "144", value: "Azusa" },
  { key: "145", value: "Bad Gastein" },
  { key: "146", value: "Bad Hofgastein" },
  { key: "147", value: "Baden" },
  { key: "148", value: "Baghdad" },
  { key: "149", value: "Baiona" },
  { key: "150", value: "Bakersfield" },
  { key: "151", value: "Baku" },
  { key: "152", value: "Baltimore" },
  { key: "153", value: "Bamako" },
  { key: "154", value: "Banda Aceh" },
  { key: "155", value: "Bandar Seri Begawan" },
  { key: "156", value: "Bandol" },
  { key: "157", value: "Banff" },
  { key: "158", value: "Bangalore" },
  { key: "159", value: "Bangkok" },
  { key: "160", value: "Bangor" },
  { key: "161", value: "Bangui" },
  { key: "162", value: "Banjul" },
  { key: "163", value: "Bar" },
  { key: "164", value: "Bar Harbor" },
  { key: "165", value: "Barcelona" },
  { key: "166", value: "Bari" },
  { key: "167", value: "Barletta" },
  { key: "168", value: "Barrie" },
  { key: "169", value: "Barstow" },
  { key: "170", value: "Basel" },
  { key: "171", value: "Basey" },
  { key: "172", value: "Basseterre" },
  { key: "173", value: "Basse-Terre" },
  { key: "174", value: "Bastia" },
  { key: "175", value: "Bata" },
  { key: "176", value: "Batam" },
  { key: "177", value: "Bath" },
  { key: "178", value: "Baton Rouge" },
  { key: "179", value: "Batu" },
  { key: "180", value: "Batumi" },
  { key: "181", value: "Bayonne" },
  { key: "182", value: "Beaulieu-sur-Mer" },
  { key: "183", value: "Beaumont" },
  { key: "184", value: "Beaune" },
  { key: "185", value: "Beersheba" },
  { key: "186", value: "Beijing" },
  { key: "187", value: "Beirut" },
  { key: "188", value: "Belek" },
  { key: "189", value: "Belfast" },
  { key: "190", value: "Belfort" },
  { key: "191", value: "Belgrade" },
  { key: "192", value: "Belize City" },
  { key: "193", value: "Bellingham" },
  { key: "194", value: "Bellinzona" },
  { key: "195", value: "Belluno" },
  { key: "196", value: "Belmopan" },
  { key: "197", value: "Belo Horizonte" },
  { key: "198", value: "Bemidji" },
  { key: "199", value: "Benalmadena" },
  { key: "200", value: "Bend" },
  { key: "201", value: "Bendigo" },
  { key: "202", value: "Benevento" },
  { key: "203", value: "Benicàssim" },
  { key: "204", value: "Benidorm" },
  { key: "205", value: "Bergamo" },
  { key: "206", value: "Bergen" },
  { key: "207", value: "Bergerac" },
  { key: "208", value: "Berkeley" },
  { key: "209", value: "Berlin" },
  { key: "210", value: "Bern" },
  { key: "211", value: "Besançon" },
  { key: "212", value: "Bethlehem" },
  { key: "213", value: "Beverly Hills" },
  { key: "214", value: "Béziers" },
  { key: "215", value: "Biarritz" },
  { key: "216", value: "Biel/Bienne" },
  { key: "217", value: "Bielefeld" },
  { key: "218", value: "Biella" },
  { key: "219", value: "Big Pine Key" },
  { key: "220", value: "Bilbao" },
  { key: "221", value: "Billings" },
  { key: "222", value: "Biloxi" },
  { key: "223", value: "Birmingham (UK)" },
  { key: "224", value: "Birmingham (U.S.)" },
  { key: "225", value: "Bishkek" },
  { key: "226", value: "Bismarck" },
  { key: "227", value: "Bissau" },
  { key: "228", value: "Blanes" },
  { key: "229", value: "Bled" },
  { key: "230", value: "Blois" },
  { key: "231", value: "Bloomington" },
  { key: "232", value: "Blumenau" },
  { key: "233", value: "Boca Chica" },
  { key: "234", value: "Boca Grande" },
  { key: "235", value: "Boca Raton" },
  { key: "236", value: "Bochum" },
  { key: "237", value: "Bodrum" },
  { key: "238", value: "Bogotá" },
  { key: "239", value: "Boise" },
  { key: "240", value: "Bologna" },
  { key: "241", value: "Bolzano" },
  { key: "242", value: "Bonifacio" },
  { key: "243", value: "Bonn" },
  { key: "244", value: "Bordeaux" },
  { key: "245", value: "Bordighera" },
  { key: "246", value: "Bormio" },
  { key: "247", value: "Boston" },
  { key: "248", value: "Boulder" },
  { key: "249", value: "Boulogne-sur-Mer" },
  { key: "250", value: "Bourges" },
  { key: "251", value: "Bowling Green" },
  { key: "252", value: "Boynton Beach" },
  { key: "253", value: "Bozeman" },
  { key: "254", value: "Bradenton" },
  { key: "255", value: "Bradford" },
  { key: "256", value: "Braga" },
  { key: "257", value: "Brampton" },
  { key: "258", value: "Brandon" },
  { key: "259", value: "Brantford" },
  { key: "260", value: "Brasilia" },
  { key: "261", value: "Bratislava" },
  { key: "262", value: "Braunschweig" },
  { key: "263", value: "Brazzaville" },
  { key: "264", value: "Breda" },
  { key: "265", value: "Bregenz" },
  { key: "266", value: "Brela" },
  { key: "267", value: "Bremen" },
  { key: "268", value: "Bremerhaven" },
  { key: "269", value: "Brescia" },
  { key: "270", value: "Brest" },
  { key: "271", value: "Briançon" },
  { key: "272", value: "Bridgeport" },
  { key: "273", value: "Bridgetown" },
  { key: "274", value: "Brigantine" },
  { key: "275", value: "Brighton" },
  { key: "276", value: "Brindisi" },
  { key: "277", value: "Brisbane" },
  { key: "278", value: "Bristol" },
  { key: "279", value: "Brixen" },
  { key: "280", value: "Brixental" },
  { key: "281", value: "Brno" },
  { key: "282", value: "Brookings" },
  { key: "283", value: "Brownsville" },
  { key: "284", value: "Bruges" },
  { key: "285", value: "Brunswick" },
  { key: "286", value: "Brussels" },
  { key: "287", value: "Bucharest" },
  { key: "288", value: "Budapest" },
  { key: "289", value: "Budva" },
  { key: "290", value: "Buenos Aires" },
  { key: "291", value: "Buffalo" },
  { key: "292", value: "Bujumbura" },
  { key: "293", value: "Bukittinggi" },
  { key: "294", value: "Burgas" },
  { key: "295", value: "Burlington (U.S.)" },
  { key: "296", value: "Burlington (Canada)" },
  { key: "297", value: "Burnt Pine" },
  { key: "298", value: "Butte" },
  { key: "299", value: "Cabo San Lucas" },
  { key: "300", value: "Cadaqués" },
  { key: "301", value: "Cádiz" },
  { key: "302", value: "Caen" },
  { key: "303", value: "Cagliari" },
  { key: "304", value: "Cagnes-sur-Mer" },
  { key: "305", value: "Cairns" },
  { key: "306", value: "Cairo" },
  { key: "307", value: "Cala Bona" },
  { key: "308", value: "Cala d'Or" },
  { key: "309", value: "Cala Millor" },
  { key: "310", value: "Cala Ratjada" },
  { key: "311", value: "Calais" },
  { key: "312", value: "Calella" },
  { key: "313", value: "Calgary" },
  { key: "314", value: "Cali" },
  { key: "315", value: "Caloundra" },
  { key: "316", value: "Calp" },
  { key: "317", value: "Caltanissetta" },
  { key: "318", value: "Calvi" },
  { key: "319", value: "Cambridge (UK)" },
  { key: "320", value: "Cambridge (U.S.)" },
  { key: "321", value: "Cambrils" },
  { key: "322", value: "Camden" },
  { key: "323", value: "Campbell River" },
  { key: "324", value: "Campinas" },
  { key: "325", value: "Campobasso" },
  { key: "326", value: "Can Pastilla" },
  { key: "327", value: "Can Picafort" },
  { key: "328", value: "Canazei" },
  { key: "329", value: "Canberra" },
  { key: "330", value: "Cancun" },
  { key: "331", value: "Cannes" },
  { key: "332", value: "Cannon Beach" },
  { key: "333", value: "Canterbury" },
  { key: "334", value: "Canton" },
  { key: "335", value: "Canyamel" },
  { key: "336", value: "Capdepera" },
  { key: "337", value: "Cape Canaveral" },
  { key: "338", value: "Cape Coral" },
  { key: "339", value: "Cape May" },
  { key: "340", value: "Cape Town" },
  { key: "341", value: "Capitola" },
  { key: "342", value: "Captiva" },
  { key: "343", value: "Caracas" },
  { key: "344", value: "Carbonia" },
  { key: "345", value: "Carcassonne" },
  { key: "346", value: "Cardiff" },
  { key: "347", value: "Carlisle" },
  { key: "348", value: "Carlsbad" },
  { key: "349", value: "Carmel-by-the-Sea" },
  { key: "350", value: "Carpi" },
  { key: "351", value: "Carpinteria" },
  { key: "352", value: "Carrara" },
  { key: "353", value: "Carson City" },
  { key: "354", value: "Cartagena (Colombia)" },
  { key: "355", value: "Cartagena (Spain)" },
  { key: "356", value: "Casablanca" },
  { key: "357", value: "Caserta" },
  { key: "358", value: "Casper" },
  { key: "359", value: "Cassis" },
  { key: "360", value: "Castellón de la Plana" },
  { key: "361", value: "Castelrotto" },
  { key: "362", value: "Castletown" },
  { key: "363", value: "Castries" },
  { key: "364", value: "Catania" },
  { key: "365", value: "Catanzaro" },
  { key: "366", value: "Caxias do Sul" },
  { key: "367", value: "Cayenne" },
  { key: "368", value: "Cebu City" },
  { key: "369", value: "Cedar Key" },
  { key: "370", value: "Cedar Rapids" },
  { key: "371", value: "Celle" },
  { key: "372", value: "Cervinia" },
  { key: "373", value: "Cesena" },
  { key: "374", value: "Český Krumlov" },
  { key: "375", value: "Çeşme" },
  { key: "376", value: "Chamonix" },
  { key: "377", value: "Chandler" },
  { key: "378", value: "Chania" },
  { key: "379", value: "Charleroi" },
  { key: "380", value: "Charleston (West Virginia)" },
  { key: "381", value: "Charleston (South Carolina)" },
  { key: "382", value: "Charlestown" },
  { key: "383", value: "Charlotte" },
  { key: "384", value: "Charlotte Amalie" },
  { key: "385", value: "Charlottetown" },
  { key: "386", value: "Chartres" },
  { key: "387", value: "Chatham" },
  { key: "388", value: "Chattanooga" },
  { key: "389", value: "Chelmsford" },
  { key: "390", value: "Chemnitz" },
  { key: "391", value: "Chennai" },
  { key: "392", value: "Cherbourg" },
  { key: "393", value: "Chesapeake" },
  { key: "394", value: "Chester" },
  { key: "395", value: "Cheyenne" },
  { key: "396", value: "Chiang Mai" },
  { key: "397", value: "Chiang Rai" },
  { key: "398", value: "Chiavari" },
  { key: "399", value: "Chicago" },
  { key: "400", value: "Chichester" },
  { key: "401", value: "Chiclayo" },
  { key: "402", value: "Chieti" },
  { key: "403", value: "Chincoteague" },
  { key: "404", value: "Chioggia" },
  { key: "405", value: "Chios" },
  { key: "406", value: "Chișinău" },
  { key: "407", value: "Chokoloskee" },
  { key: "408", value: "Chonburi" },
  { key: "409", value: "Christchurch" },
  { key: "410", value: "Christiansted" },
  { key: "411", value: "Chula Vista" },
  { key: "412", value: "Chur" },
  { key: "413", value: "Cincinnati" },
  { key: "414", value: "Ciutadella de Menorca" },
  { key: "415", value: "Civitavecchia" },
  { key: "416", value: "Clarksville" },
  { key: "417", value: "Clearwater" },
  { key: "418", value: "Clearwater Beach" },
  { key: "419", value: "Clermont-Ferrand" },
  { key: "420", value: "Cleveland" },
  { key: "421", value: "Cockburn Town" },
  { key: "422", value: "Cocoa Beach" },
  { key: "423", value: "Coconut Creek" },
  { key: "424", value: "Coimbra" },
  { key: "425", value: "Collioure" },
  { key: "426", value: "Colmar" },
  { key: "427", value: "Cologne" },
  { key: "428", value: "Colombo" },
  { key: "429", value: "Colón" },
  { key: "430", value: "Colonia del Sacramento" },
  { key: "431", value: "Colorado Springs" },
  { key: "432", value: "Columbia (South Carolina)" },
  { key: "433", value: "Columbia (Missouri)" },
  { key: "434", value: "Columbus" },
  { key: "435", value: "Como" },
  { key: "436", value: "Conakry" },
  { key: "437", value: "Concepción" },
  { key: "438", value: "Concord" },
  { key: "439", value: "Conil de la Frontera" },
  { key: "440", value: "Conway" },
  { key: "441", value: "Copenhagen" },
  { key: "442", value: "Coral Springs" },
  { key: "443", value: "Córdoba (Argentina)" },
  { key: "444", value: "Córdoba (Spain)" },
  { key: "445", value: "Corfu" },
  { key: "446", value: "Corinth" },
  { key: "447", value: "Cork" },
  { key: "448", value: "Coro" },
  { key: "449", value: "Coron Town" },
  { key: "450", value: "Corpus Christi" },
  { key: "451", value: "Corralejo" },
  { key: "452", value: "Cortina d'Ampezzo" },
  { key: "453", value: "Cosenza" },
  { key: "454", value: "Costa Adeje" },
  { key: "455", value: "Cotabato City" },
  { key: "456", value: "Cottbus" },
  { key: "457", value: "Courchevel" },
  { key: "458", value: "Courmayeur" },
  { key: "459", value: "Courtenay" },
  { key: "460", value: "Coventry" },
  { key: "461", value: "Covington" },
  { key: "462", value: "Coxen Hole" },
  { key: "463", value: "Coyhaique" },
  { key: "464", value: "Cozumel" },
  { key: "465", value: "Crans-Montana" },
  { key: "466", value: "Cremona" },
  { key: "467", value: "Crotone" },
  { key: "468", value: "Cruz Bay" },
  { key: "469", value: "Cudjoe Key" },
  { key: "470", value: "Cuenca (Ecuador)" },
  { key: "471", value: "Cuenca (Spain)" },
  { key: "472", value: "Cumaná" },
  { key: "473", value: "Cuneo" },
  { key: "474", value: "Cusco" },
  { key: "475", value: "Da Nang" },
  { key: "476", value: "Dachau" },
  { key: "477", value: "Dahab" },
  { key: "478", value: "Dakar" },
  { key: "479", value: "Dallas" },
  { key: "480", value: "Damascus" },
  { key: "481", value: "Dana Point" },
  { key: "482", value: "Dar es Salaam" },
  { key: "483", value: "Darien" },
  { key: "484", value: "Darmstadt" },
  { key: "485", value: "Darwin" },
  { key: "486", value: "Daugavpils" },
  { key: "487", value: "Dauphin Island" },
  { key: "488", value: "Davao City" },
  { key: "489", value: "Davenport" },
  { key: "490", value: "Davos" },
  { key: "491", value: "Dayton" },
  { key: "492", value: "Daytona Beach" },
  { key: "493", value: "Deauville" },
  { key: "494", value: "Decatur" },
  { key: "495", value: "Deerfield Beach" },
  { key: "496", value: "Del Mar" },
  { key: "497", value: "Delft" },
  { key: "498", value: "Delhi" },
  { key: "499", value: "Delray Beach" },
  { key: "500", value: "Den Bosch" },
  { key: "501", value: "Denia" },
  { key: "502", value: "Denpasar" },
  { key: "503", value: "Denton" },
  { key: "504", value: "Denver" },
  { key: "505", value: "Derby" },
  { key: "506", value: "Derry" },
  { key: "507", value: "Des Moines" },
  { key: "508", value: "Detroit" },
  { key: "509", value: "Dhaka" },
  { key: "510", value: "Didim" },
  { key: "511", value: "Dieppe" },
  { key: "512", value: "Dijon" },
  { key: "513", value: "Dili" },
  { key: "514", value: "Djibouti" },
  { key: "515", value: "Dodoma" },
  { key: "516", value: "Doha" },
  { key: "517", value: "Dolomiti Superski" },
  { key: "518", value: "Dordrecht" },
  { key: "519", value: "Dorfgastein" },
  { key: "520", value: "Dortmund" },
  { key: "521", value: "Dothan" },
  { key: "522", value: "Douala" },
  { key: "523", value: "Douglas" },
  { key: "524", value: "Dover (Delaware)" },
  { key: "525", value: "Dover (New Hampshire)" },
  { key: "526", value: "Dresden" },
  { key: "527", value: "Dubai" },
  { key: "528", value: "Dublin" },
  { key: "529", value: "Dubrovnik" },
  { key: "530", value: "Duisburg" },
  { key: "531", value: "Duluth" },
  { key: "532", value: "Dumaguete" },
  { key: "533", value: "Dumai" },
  { key: "534", value: "Duncan" },
  { key: "535", value: "Dundalk" },
  { key: "536", value: "Dundee" },
  { key: "537", value: "Dunedin" },
  { key: "538", value: "Dunkirk" },
  { key: "539", value: "Durham (UK)" },
  { key: "540", value: "Durham (U.S.)" },
  { key: "541", value: "Dushanbe" },
  { key: "542", value: "Düsseldorf" },
  { key: "543", value: "Eastbourne" },
  { key: "544", value: "Eau Claire" },
  { key: "545", value: "Edgartown" },
  { key: "546", value: "Edinburgh" },
  { key: "547", value: "Edmonton" },
  { key: "548", value: "Eilat" },
  { key: "549", value: "Eindhoven" },
  { key: "550", value: "El Nido" },
  { key: "551", value: "El Paso" },
  { key: "552", value: "Elche" },
  { key: "553", value: "Elizabeth" },
  { key: "554", value: "Elko" },
  { key: "555", value: "Ellmau" },
  { key: "556", value: "Elm" },
  { key: "557", value: "Empuriabrava" },
  { key: "558", value: "Encinitas" },
  { key: "559", value: "Engelberg" },
  { key: "560", value: "Englewood Beach" },
  { key: "561", value: "Enna" },
  { key: "562", value: "Enschede" },
  { key: "563", value: "Épinal" },
  { key: "564", value: "Erfurt" },
  { key: "565", value: "Erie" },
  { key: "566", value: "Erlangen" },
  { key: "567", value: "Esbjerg" },
  { key: "568", value: "Espace Killy" },
  { key: "569", value: "Essaouira" },
  { key: "570", value: "Essen" },
  { key: "571", value: "Estepona" },
  { key: "572", value: "Eugene" },
  { key: "573", value: "Eureka" },
  { key: "574", value: "Evansville" },
  { key: "575", value: "Everett" },
  { key: "576", value: "Everglades City" },
  { key: "577", value: "Exeter" },
  { key: "578", value: "Èze" },
  { key: "579", value: "Faenza" },
  { key: "580", value: "Fairbanks" },
  { key: "581", value: "Fakaofo" },
  { key: "582", value: "Falmouth" },
  { key: "583", value: "Famagusta" },
  { key: "584", value: "Fano" },
  { key: "585", value: "Fargo" },
  { key: "586", value: "Faro" },
  { key: "587", value: "Fayetteville (North Carolina)" },
  { key: "588", value: "Fayetteville (Arkansas)" },
  { key: "589", value: "Fermo" },
  { key: "590", value: "Fernandina Beach" },
  { key: "591", value: "Ferrara" },
  { key: "592", value: "Fethiye" },
  { key: "593", value: "Fez" },
  { key: "594", value: "Fieberbrunn" },
  { key: "595", value: "Filzmoos" },
  { key: "596", value: "Finale Ligure" },
  { key: "597", value: "Fisher Island" },
  { key: "598", value: "Fiumicino" },
  { key: "599", value: "Flagstaff" },
  { key: "600", value: "Flaine" },
  { key: "601", value: "Flint" },
  { key: "602", value: "Florence" },
  { key: "603", value: "Florence (Alabama)" },
  { key: "604", value: "Flores" },
  { key: "605", value: "Foggia" },
  { key: "606", value: "Folgarida" },
  { key: "607", value: "Fontana" },
  { key: "608", value: "Forlì" },
  { key: "609", value: "Fort Collins" },
  { key: "610", value: "Fort Lauderdale" },
  { key: "611", value: "Fort Myers" },
  { key: "612", value: "Fort Myers Beach" },
  { key: "613", value: "Fort Pierce" },
  { key: "614", value: "Fort Smith" },
  { key: "615", value: "Fort Wayne" },
  { key: "616", value: "Fort Worth" },
  { key: "617", value: "Fort-de-France" },
  { key: "618", value: "Forte dei Marmi" },
  { key: "619", value: "Foz do Iguaçu" },
  { key: "620", value: "Frankfort" },
  { key: "621", value: "Frankfurt am Main" },
  { key: "622", value: "Franklin" },
  { key: "623", value: "Frederick" },
  { key: "624", value: "Fredericton" },
  { key: "625", value: "Frederiksted" },
  { key: "626", value: "Freeport" },
  { key: "627", value: "Freetown" },
  { key: "628", value: "Freiburg" },
  { key: "629", value: "Fremont" },
  { key: "630", value: "Fresno" },
  { key: "631", value: "Fribourg" },
  { key: "632", value: "Frosinone" },
  { key: "633", value: "Fuengirola" },
  { key: "634", value: "Fujairah" },
  { key: "635", value: "Fukuoka" },
  { key: "636", value: "Funafuti" },
  { key: "637", value: "Funchal" },
  { key: "638", value: "Gaborone" },
  { key: "639", value: "Gainesville" },
  { key: "640", value: "Galtür" },
  { key: "641", value: "Galway" },
  { key: "642", value: "Gandia" },
  { key: "643", value: "Garden Grove" },
  { key: "644", value: "Garland" },
  { key: "645", value: "Gastonia" },
  { key: "646", value: "Gatineau" },
  { key: "647", value: "Gaza City" },
  { key: "648", value: "Gdansk" },
  { key: "649", value: "Gdynia" },
  { key: "650", value: "Geelong" },
  { key: "651", value: "Gelsenkirchen" },
  { key: "652", value: "Geneva" },
  { key: "653", value: "Genoa" },
  { key: "654", value: "George Town (Cayman Islands)" },
  { key: "655", value: "George Town (Malaysia)" },
  { key: "656", value: "Georgetown" },
  { key: "657", value: "Ghent" },
  { key: "658", value: "Gijón" },
  { key: "659", value: "Gilbert" },
  { key: "660", value: "Girona" },
  { key: "661", value: "Gitega" },
  { key: "662", value: "Giza" },
  { key: "663", value: "Glasgow" },
  { key: "664", value: "Glendale (Arizona)" },
  { key: "665", value: "Glendale (California)" },
  { key: "666", value: "Gloucester" },
  { key: "667", value: "Gold Coast" },
  { key: "668", value: "Gorizia" },
  { key: "669", value: "Gosau" },
  { key: "670", value: "Gothenburg" },
  { key: "671", value: "Göttingen" },
  { key: "672", value: "Gouda" },
  { key: "673", value: "Granada (Spain)" },
  { key: "674", value: "Granada (Nicaragua)" },
  { key: "675", value: "Grand Forks" },
  { key: "676", value: "Grand Island" },
  { key: "677", value: "Grand Junction" },
  { key: "678", value: "Grand Prairie" },
  { key: "679", value: "Grand Rapids" },
  { key: "680", value: "Grande Prairie" },
  { key: "681", value: "Granville" },
  { key: "682", value: "Grasse" },
  { key: "683", value: "Graz" },
  { key: "684", value: "Great Falls" },
  { key: "685", value: "Greeley" },
  { key: "686", value: "Green Bay" },
  { key: "687", value: "Greensboro" },
  { key: "688", value: "Greenville NC" },
  { key: "689", value: "Greenville SC" },
  { key: "690", value: "Grenoble" },
  { key: "691", value: "Grindelwald" },
  { key: "692", value: "Groningen" },
  { key: "693", value: "Grossarl" },
  { key: "694", value: "Grosseto" },
  { key: "695", value: "Grover Beach" },
  { key: "696", value: "Gstaad" },
  { key: "697", value: "Guadalajara" },
  { key: "698", value: "Guadalupe" },
  { key: "699", value: "Guangzhou" },
  { key: "700", value: "Guatemala City" },
  { key: "701", value: "Guayaquil" },
  { key: "702", value: "Guelph" },
  { key: "703", value: "Guimarães" },
  { key: "704", value: "Gulf Shores" },
  { key: "705", value: "Gulfport" },
  { key: "706", value: "Gustavia" },
  { key: "707", value: "Haarlem" },
  { key: "708", value: "Haifa" },
  { key: "709", value: "Half Moon Bay" },
  { key: "710", value: "Halifax" },
  { key: "711", value: "Halle" },
  { key: "712", value: "Hamburg" },
  { key: "713", value: "Hamilton (Bermuda)" },
  { key: "714", value: "Hamilton (Canada)" },
  { key: "715", value: "Hamilton (New Zealand)" },
  { key: "716", value: "Hampton" },
  { key: "717", value: "Hanford" },
  { key: "718", value: "Hangzhou" },
  { key: "719", value: "Hannover" },
  { key: "720", value: "Hanoi" },
  { key: "721", value: "Harare" },
  { key: "722", value: "Hargeisa" },
  { key: "723", value: "Harrisburg" },
  { key: "724", value: "Hartford" },
  { key: "725", value: "Hasselt" },
  { key: "726", value: "Hastings" },
  { key: "727", value: "Hat Yai" },
  { key: "728", value: "Hattiesburg" },
  { key: "729", value: "Havana" },
  { key: "730", value: "Heidelberg" },
  { key: "731", value: "Heilbronn" },
  { key: "732", value: "Heiligenblut" },
  { key: "733", value: "Helena" },
  { key: "734", value: "Helsinki" },
  { key: "735", value: "Henderson" },
  { key: "736", value: "Heraklion" },
  { key: "737", value: "Herceg Novi" },
  { key: "738", value: "Hereford" },
  { key: "739", value: "Hermosa Beach" },
  { key: "740", value: "Hervey Bay" },
  { key: "741", value: "Hialeah" },
  { key: "742", value: "Hillsboro" },
  { key: "743", value: "Hinterglemm" },
  { key: "744", value: "Hinterstoder" },
  { key: "745", value: "Hiroshima" },
  { key: "746", value: "Hoi An" },
  { key: "747", value: "Hobart" },
  { key: "748", value: "Ho Chi Minh City" },
  { key: "749", value: "Holbrook" },
  { key: "750", value: "Hollywood (Florida)" },
  { key: "751", value: "Honfleur" },
  { key: "752", value: "Hong Kong" },
  { key: "753", value: "Honiara" },
  { key: "754", value: "Honolulu" },
  { key: "755", value: "Horsens" },
  { key: "756", value: "Hot Springs" },
  { key: "757", value: "Houston" },
  { key: "758", value: "Hua Hin" },
  { key: "759", value: "Hue" },
  { key: "760", value: "Huntington" },
  { key: "761", value: "Huntington Beach" },
  { key: "762", value: "Huntsville" },
  { key: "763", value: "Hurghada" },
  { key: "764", value: "Hvar" },
  { key: "765", value: "Hyères" },
  { key: "766", value: "Ibiza Town" },
  { key: "767", value: "Iloilo City" },
  { key: "768", value: "Imola" },
  { key: "769", value: "Imperia" },
  { key: "770", value: "Inca" },
  { key: "771", value: "Indianapolis" },
  { key: "772", value: "Ingolstadt" },
  { key: "773", value: "Innsbruck" },
  { key: "774", value: "Interlaken" },
  { key: "775", value: "Inverness" },
  { key: "776", value: "Ioannina" },
  { key: "777", value: "Iqaluit" },
  { key: "778", value: "Iquitos" },
  { key: "779", value: "Irvine" },
  { key: "780", value: "Irving" },
  { key: "781", value: "Ischgl" },
  { key: "782", value: "Isernia" },
  { key: "783", value: "Lahore" },
  { key: "784", value: "Islamorada" },
  { key: "785", value: "Istanbul" },
  { key: "786", value: "İzmir" },
  { key: "787", value: "Izola" },
  { key: "788", value: "Jackson" },
  { key: "789", value: "Jackson (Tennessee)" },
  { key: "790", value: "Jacksonville" },
  { key: "791", value: "Jaipur" },
  { key: "792", value: "Jakarta" },
  { key: "793", value: "Jefferson City" },
  { key: "794", value: "Jekyll Island" },
  { key: "795", value: "Jena" },
  { key: "796", value: "Jerez de la Frontera" },
  { key: "797", value: "Jersey City" },
  { key: "798", value: "Jerusalem" },
  { key: "799", value: "Johannesburg" },
  { key: "800", value: "Johnson City" },
  { key: "801", value: "Joinville" },
  { key: "802", value: "Jonesboro" },
  { key: "803", value: "Juan Griego" },
  { key: "804", value: "Juan-les-Pins" },
  { key: "805", value: "Juba" },
  { key: "806", value: "Juiz de Fora" },
  { key: "807", value: "Juneau" },
  { key: "808", value: "Jungfrau" },
  { key: "809", value: "Jupiter" },
  { key: "810", value: "Jupiter Island" },
  { key: "811", value: "Jūrmala" },
  { key: "812", value: "Kabul" },
  { key: "813", value: "Kaiserslautern" },
  { key: "814", value: "Kalamata" },
  { key: "815", value: "Kalamazoo" },
  { key: "816", value: "Kamloops" },
  { key: "817", value: "Kampala" },
  { key: "818", value: "Kanchanaburi" },
  { key: "819", value: "Kansas City" },
  { key: "820", value: "Kansas City (Kansas)" },
  { key: "821", value: "Kappl" },
  { key: "822", value: "Kaprun" },
  { key: "823", value: "Islamabad" },
  { key: "824", value: "Karlovy Vary" },
  { key: "825", value: "Karlsruhe" },
  { key: "826", value: "Kassel" },
  { key: "827", value: "Kastoria" },
  { key: "828", value: "Kathmandu" },
  { key: "829", value: "Kaunas" },
  { key: "830", value: "Kavala" },
  { key: "831", value: "Kearney" },
  { key: "832", value: "Keene" },
  { key: "833", value: "Kelowna" },
  { key: "834", value: "Kemer" },
  { key: "835", value: "Kenosha" },
  { key: "836", value: "Key Biscayne" },
  { key: "837", value: "Key Largo" },
  { key: "838", value: "Key West" },
  { key: "839", value: "Khao Lak" },
  { key: "840", value: "Khartoum" },
  { key: "841", value: "Kiel" },
  { key: "842", value: "Kigali" },
  { key: "843", value: "Kilkenny" },
  { key: "844", value: "Kingman" },
  { key: "845", value: "Kingston (Jamaica)" },
  { key: "846", value: "Kingston (Norfolk Island)" },
  { key: "847", value: "Kingston (Canada)" },
  { key: "848", value: "Kingston upon Hull" },
  { key: "849", value: "Kingstown" },
  { key: "850", value: "Kinshasa" },
  { key: "851", value: "Kissimmee" },
  { key: "852", value: "Kitchener" },
  { key: "853", value: "Kitzbühel" },
  { key: "854", value: "Klagenfurt" },
  { key: "855", value: "Klaipėda" },
  { key: "856", value: "Knoxville" },
  { key: "857", value: "Kobe" },
  { key: "858", value: "Koblenz" },
  { key: "859", value: "Kolding" },
  { key: "860", value: "Kolkata" },
  { key: "861", value: "Komotini" },
  { key: "862", value: "Koper" },
  { key: "863", value: "Koror" },
  { key: "864", value: "Kos" },
  { key: "865", value: "Košice" },
  { key: "866", value: "Kotor" },
  { key: "867", value: "Krabi" },
  { key: "868", value: "Krakow" },
  { key: "869", value: "Kralendijk" },
  { key: "870", value: "Krefeld" },
  { key: "871", value: "Kuala Lumpur" },
  { key: "872", value: "Kuşadası" },
  { key: "873", value: "Kuta" },
  { key: "874", value: "Kutná Hora" },
  { key: "875", value: "Kuwait City" },
  { key: "876", value: "Kyiv" },
  { key: "877", value: "Kyoto" },
  { key: "878", value: "Kyrenia" },
  { key: "879", value: "La Ceiba" },
  { key: "880", value: "La Ciotat" },
  { key: "881", value: "La Clusaz" },
  { key: "882", value: "La Laguna" },
  { key: "883", value: "La Maddalena" },
  { key: "884", value: "La Manga" },
  { key: "885", value: "La Paz" },
  { key: "886", value: "La Plagne" },
  { key: "887", value: "La Plata" },
  { key: "888", value: "La Rochelle" },
  { key: "889", value: "La Romana" },
  { key: "890", value: "La Serena" },
  { key: "891", value: "La Seyne-sur-Mer" },
  { key: "892", value: "La Spezia" },
  { key: "893", value: "La Thuile" },
  { key: "894", value: "Laax" },
  { key: "895", value: "Labasa" },
  { key: "896", value: "Labrador City" },
  { key: "897", value: "Labuan Bajo" },
  { key: "898", value: "Ladysmith" },
  { key: "899", value: "Lafayette (Indiana)" },
  { key: "900", value: "Lafayette (Louisiana)" },
  { key: "901", value: "Lagos (Nigeria)" },
  { key: "902", value: "Lagos (Portugal)" },
  { key: "903", value: "Laguna Beach" },
  { key: "904", value: "Karachi" },
  { key: "905", value: "Lakeland" },
  { key: "906", value: "Lalitpur" },
  { key: "907", value: "Lamezia Terme" },
  { key: "908", value: "Lancaster" },
  { key: "909", value: "Lancaster (U.S.)" },
  { key: "910", value: "Landshut" },
  { key: "911", value: "Lansing" },
  { key: "912", value: "L'Aquila" },
  { key: "913", value: "Laredo" },
  { key: "914", value: "Largo" },
  { key: "915", value: "Larnaca" },
  { key: "916", value: "Las Cruces" },
  { key: "917", value: "Las Palmas" },
  { key: "918", value: "Las Vegas" },
  { key: "919", value: "Latina" },
  { key: "920", value: "Lausanne" },
  { key: "921", value: "Lautoka" },
  { key: "922", value: "Laval" },
  { key: "923", value: "Lawton" },
  { key: "924", value: "Layton" },
  { key: "925", value: "Le Havre" },
  { key: "926", value: "Le Lavandou" },
  { key: "927", value: "Le Mans" },
  { key: "928", value: "Le Puy-en-Velay" },
  { key: "929", value: "Lecce" },
  { key: "930", value: "Lecco" },
  { key: "931", value: "Lech" },
  { key: "932", value: "Leeds" },
  { key: "933", value: "Legian" },
  { key: "934", value: "Legnano" },
  { key: "935", value: "Leicester" },
  { key: "936", value: "Leiden" },
  { key: "937", value: "Leipzig" },
  { key: "938", value: "Lemgo" },
  { key: "939", value: "Leogang" },
  { key: "940", value: "León" },
  { key: "941", value: "Les Arcs" },
  { key: "942", value: "Les Deux Alpes" },
  { key: "943", value: "Les Gets" },
  { key: "944", value: "Les Houches" },
  { key: "945", value: "Les Menuires" },
  { key: "946", value: "Lethbridge" },
  { key: "947", value: "Leuven" },
  { key: "948", value: "Leverkusen" },
  { key: "949", value: "Lexington" },
  { key: "950", value: "Liberec" },
  { key: "951", value: "Libreville" },
  { key: "952", value: "Lichfield" },
  { key: "953", value: "Lido Key" },
  { key: "954", value: "Liège" },
  { key: "955", value: "Lienz" },
  { key: "956", value: "Liepāja" },
  { key: "957", value: "Lille" },
  { key: "958", value: "Lilongwe" },
  { key: "959", value: "Lima" },
  { key: "960", value: "Limassol" },
  { key: "961", value: "Limerick" },
  { key: "962", value: "Limoges" },
  { key: "963", value: "Lincoln" },
  { key: "964", value: "Lincoln" },
  { key: "965", value: "Lindos" },
  { key: "966", value: "Linz" },
  { key: "967", value: "Lisbon" },
  { key: "968", value: "Lisburn" },
  { key: "969", value: "Little Rock" },
  { key: "970", value: "Liverpool" },
  { key: "971", value: "Livigno" },
  { key: "972", value: "Livorno" },
  { key: "973", value: "Ljubljana" },
  { key: "974", value: "Lloret de Mar" },
  { key: "975", value: "Llucmajor" },
  { key: "976", value: "Loano" },
  { key: "977", value: "Locarno" },
  { key: "978", value: "Lodi" },
  { key: "979", value: "Lodz" },
  { key: "980", value: "Logan" },
  { key: "981", value: "Logroño" },
  { key: "982", value: "Lomé" },
  { key: "983", value: "London (Canada)" },
  { key: "984", value: "London (UK)" },
  { key: "985", value: "Londrina" },
  { key: "986", value: "Long Beach" },
  { key: "987", value: "Long Beach (New York)" },
  { key: "988", value: "Long Branch" },
  { key: "989", value: "Longboat Key" },
  { key: "990", value: "Longview (Texas)" },
  { key: "991", value: "Longview (Washington)" },
  { key: "992", value: "Lorain" },
  { key: "993", value: "Los Alamos" },
  { key: "994", value: "Los Angeles" },
  { key: "995", value: "Los Cabos" },
  { key: "996", value: "Los Cristianos" },
  { key: "997", value: "Louisville" },
  { key: "998", value: "Lourdes" },
  { key: "999", value: "Loutraki" },
  { key: "1000", value: "Louvain-la-Neuve" },
  { key: "1001", value: "Lowell" },
  { key: "1002", value: "Luanda" },
  { key: "1003", value: "Lubbock" },
  { key: "1004", value: "Lübeck" },
  { key: "1005", value: "Lublin" },
  { key: "1006", value: "Lucca" },
  { key: "1007", value: "Lucerne" },
  { key: "1008", value: "Lugano" },
  { key: "1009", value: "Luganville" },
  { key: "1010", value: "Lund" },
  { key: "1011", value: "Lusaka" },
  { key: "1012", value: "Luxembourg" },
  { key: "1013", value: "Luxor" },
  { key: "1014", value: "Lyon" },
  { key: "1015", value: "Maastricht" },
  { key: "1016", value: "Macerata" },
  { key: "1017", value: "Machu Picchu" },
  { key: "1018", value: "Macon" },
  { key: "1019", value: "Madera" },
  { key: "1020", value: "Madison" },
  { key: "1021", value: "Madonna di Campiglio" },
  { key: "1022", value: "Madrid" },
  { key: "1023", value: "Magaluf" },
  { key: "1024", value: "Magdeburg" },
  { key: "1025", value: "Mahón" },
  { key: "1026", value: "Mainz" },
  { key: "1027", value: "Majuro" },
  { key: "1028", value: "Makarska" },
  { key: "1029", value: "Malabo" },
  { key: "1030", value: "Malaga" },
  { key: "1031", value: "Malang" },
  { key: "1032", value: "Maldonado" },
  { key: "1033", value: "Malé" },
  { key: "1034", value: "Malia" },
  { key: "1035", value: "Malibu" },
  { key: "1036", value: "Malmö" },
  { key: "1037", value: "Manacor" },
  { key: "1038", value: "Manado" },
  { key: "1039", value: "Managua" },
  { key: "1040", value: "Manama" },
  { key: "1041", value: "Manchester (UK)" },
  { key: "1042", value: "Manchester (U.S.)" },
  { key: "1043", value: "Máncora" },
  { key: "1044", value: "Mandalika" },
  { key: "1045", value: "Manhattan Beach" },
  { key: "1046", value: "Manhattan, KS" },
  { key: "1047", value: "Manila" },
  { key: "1048", value: "Mannheim" },
  { key: "1049", value: "Manosque" },
  { key: "1050", value: "Mantua" },
  { key: "1051", value: "Maputo" },
  { key: "1052", value: "Mar del Plata" },
  { key: "1053", value: "Maracaibo" },
  { key: "1054", value: "Marathon" },
  { key: "1055", value: "Marbella" },
  { key: "1056", value: "Marco Island" },
  { key: "1057", value: "Maria Alm" },
  { key: "1058", value: "Maribor" },
  { key: "1059", value: "Marigot" },
  { key: "1060", value: "Markham" },
  { key: "1061", value: "Marmaris" },
  { key: "1062", value: "Maroochydore" },
  { key: "1063", value: "Marquette" },
  { key: "1064", value: "Marrakesh" },
  { key: "1065", value: "Marsa Alam" },
  { key: "1066", value: "Marsala" },
  { key: "1067", value: "Marseille" },
  { key: "1068", value: "Martigues" },
  { key: "1069", value: "Masaya" },
  { key: "1070", value: "Maseru" },
  { key: "1071", value: "Maspalomas" },
  { key: "1072", value: "Massa" },
  { key: "1073", value: "Mataram" },
  { key: "1074", value: "Matera" },
  { key: "1075", value: "Mayrhofen" },
  { key: "1076", value: "Mazara del Vallo" },
  { key: "1077", value: "Mbabane" },
  { key: "1078", value: "McKinney" },
  { key: "1079", value: "Mechelen" },
  { key: "1080", value: "Medan" },
  { key: "1081", value: "Medellín" },
  { key: "1082", value: "Medford" },
  { key: "1083", value: "Megève" },
  { key: "1084", value: "Melbourne (Australia)" },
  { key: "1085", value: "Melbourne (U.S.)" },
  { key: "1086", value: "Memphis" },
  { key: "1087", value: "Menton" },
  { key: "1088", value: "Merano" },
  { key: "1089", value: "Merced" },
  { key: "1090", value: "Meribel" },
  { key: "1091", value: "Mérida (Spain)" },
  { key: "1092", value: "Mérida (Venezuela)" },
  { key: "1093", value: "Meridian" },
  { key: "1094", value: "Merritt Island" },
  { key: "1095", value: "Mesa" },
  { key: "1096", value: "Messina" },
  { key: "1097", value: "Mestre" },
  { key: "1098", value: "Metz" },
  { key: "1099", value: "Mexico City" },
  { key: "1100", value: "Miami" },
  { key: "1101", value: "Middelburg" },
  { key: "1102", value: "Midland" },
  { key: "1103", value: "Mijas" },
  { key: "1104", value: "Milan" },
  { key: "1105", value: "Milford" },
  { key: "1106", value: "Millau" },
  { key: "1107", value: "Milwaukee" },
  { key: "1108", value: "Mindelo" },
  { key: "1109", value: "Minneapolis" },
  { key: "1110", value: "Minot" },
  { key: "1111", value: "Minsk" },
  { key: "1112", value: "Miramar" },
  { key: "1113", value: "Mishawaka" },
  { key: "1114", value: "Mississauga" },
  { key: "1115", value: "Missoula" },
  { key: "1116", value: "Moab" },
  { key: "1117", value: "Mobile" },
  { key: "1118", value: "Modena" },
  { key: "1119", value: "Modesto" },
  { key: "1120", value: "Modica" },
  { key: "1121", value: "Moena" },
  { key: "1122", value: "Mogadishu" },
  { key: "1123", value: "Mogi das Cruzes" },
  { key: "1124", value: "Mombasa" },
  { key: "1125", value: "Monaco City" },
  { key: "1126", value: "Mönchengladbach" },
  { key: "1127", value: "Moncton" },
  { key: "1128", value: "Monrovia (Liberia)" },
  { key: "1129", value: "Monrovia (U.S.)" },
  { key: "1130", value: "Mons" },
  { key: "1131", value: "Monschau" },
  { key: "1132", value: "Monte Carlo" },
  { key: "1133", value: "Monte Rosa" },
  { key: "1134", value: "Montego Bay" },
  { key: "1135", value: "Montepulciano" },
  { key: "1136", value: "Monterey" },
  { key: "1137", value: "Montevideo" },
  { key: "1138", value: "Montgomery" },
  { key: "1139", value: "Montluçon" },
  { key: "1140", value: "Montpelier" },
  { key: "1141", value: "Montpellier" },
  { key: "1142", value: "Montreal" },
  { key: "1143", value: "Montreux" },
  { key: "1144", value: "Monza" },
  { key: "1145", value: "Moose Jaw" },
  { key: "1146", value: "Moraira" },
  { key: "1147", value: "Moreno Valley" },
  { key: "1148", value: "Morgantown" },
  { key: "1149", value: "Moroni" },
  { key: "1150", value: "Morro Bay" },
  { key: "1151", value: "Morzine" },
  { key: "1152", value: "Moscow" },
  { key: "1153", value: "Mount Vernon" },
  { key: "1154", value: "Mountain View" },
  { key: "1155", value: "Moutier" },
  { key: "1156", value: "Mulhouse" },
  { key: "1157", value: "Mumbai" },
  { key: "1158", value: "Munich" },
  { key: "1159", value: "Münster" },
  { key: "1160", value: "Murcia" },
  { key: "1161", value: "Murfreesboro" },
  { key: "1162", value: "Murter" },
  { key: "1163", value: "Mykonos" },
  { key: "1164", value: "Mytilene" },
  { key: "1165", value: "Nadi" },
  { key: "1166", value: "Nafplio" },
  { key: "1167", value: "Nagoya" },
  { key: "1168", value: "Nags Head" },
  { key: "1169", value: "Nairobi" },
  { key: "1170", value: "Namur" },
  { key: "1171", value: "Nanaimo" },
  { key: "1172", value: "Nancy" },
  { key: "1173", value: "Nantes" },
  { key: "1174", value: "Napa" },
  { key: "1175", value: "Naples (Italy)" },
  { key: "1176", value: "Naples (U.S.)" },
  { key: "1177", value: "Narbonne" },
  { key: "1178", value: "Narva" },
  { key: "1179", value: "Nashua" },
  { key: "1180", value: "Nashville" },
  { key: "1181", value: "Nassau" },
  { key: "1182", value: "Naxos" },
  { key: "1183", value: "Nazareth" },
  { key: "1184", value: "N'Djamena" },
  { key: "1185", value: "Negril" },
  { key: "1186", value: "Neiafu" },
  { key: "1187", value: "Nelson" },
  { key: "1188", value: "Nerja" },
  { key: "1189", value: "Netanya" },
  { key: "1190", value: "Nevers" },
  { key: "1191", value: "New Haven" },
  { key: "1192", value: "New London" },
  { key: "1193", value: "New Orleans" },
  { key: "1194", value: "New Smyrna Beach" },
  { key: "1195", value: "New York City" },
  { key: "1196", value: "Newark" },
  { key: "1197", value: "Newcastle (Australia)" },
  { key: "1198", value: "Newcastle (UK)" },
  { key: "1199", value: "Newport (UK)" },
  { key: "1200", value: "Newport (Rhode Island)" },
  { key: "1201", value: "Newport (Vermont)" },
  { key: "1202", value: "Newport Beach" },
  { key: "1203", value: "Newport News" },
  { key: "1204", value: "Newry" },
  { key: "1205", value: "Ngerulmud" },
  { key: "1206", value: "Nha Trang" },
  { key: "1207", value: "Niagara Falls (U.S.)" },
  { key: "1208", value: "Niagara Falls (Canada)" },
  { key: "1209", value: "Niamey" },
  { key: "1210", value: "Nice" },
  { key: "1211", value: "Nicosia" },
  { key: "1212", value: "Nijmegen" },
  { key: "1213", value: "Nimes" },
  { key: "1214", value: "Niort" },
  { key: "1215", value: "Noosa Heads" },
  { key: "1216", value: "Norfolk" },
  { key: "1217", value: "Normal" },
  { key: "1218", value: "Norman" },
  { key: "1219", value: "North Captiva Island" },
  { key: "1220", value: "North Las Vegas" },
  { key: "1221", value: "North Port" },
  { key: "1222", value: "Norwalk" },
  { key: "1223", value: "Norwich" },
  { key: "1224", value: "Nottingham" },
  { key: "1225", value: "Nouakchott" },
  { key: "1226", value: "Novara" },
  { key: "1227", value: "Novigrad" },
  { key: "1228", value: "Nukuʻalofa" },
  { key: "1229", value: "Nukunonu" },
  { key: "1230", value: "Nuoro" },
  { key: "1231", value: "Nürnberg" },
  { key: "1232", value: "Nur-Sultan" },
  { key: "1233", value: "Nusa Dua" },
  { key: "1234", value: "Nuuk" },
  { key: "1235", value: "Nyon" },
  { key: "1236", value: "Oakland" },
  { key: "1237", value: "Oakville" },
  { key: "1238", value: "Oaxaca" },
  { key: "1239", value: "Obergurgl" },
  { key: "1240", value: "Oberhausen" },
  { key: "1241", value: "Ocala" },
  { key: "1242", value: "Ocean City" },
  { key: "1243", value: "Ocean Grove" },
  { key: "1244", value: "Oceanside" },
  { key: "1245", value: "Ocho Rios" },
  { key: "1246", value: "Odense" },
  { key: "1247", value: "Odessa" },
  { key: "1248", value: "Ogden" },
  { key: "1249", value: "Oia" },
  { key: "1250", value: "Oklahoma City" },
  { key: "1251", value: "Olbia" },
  { key: "1252", value: "Oldenburg" },
  { key: "1253", value: "Olomouc" },
  { key: "1254", value: "Olympia" },
  { key: "1255", value: "Omaha" },
  { key: "1256", value: "Omoa" },
  { key: "1257", value: "Opatija" },
  { key: "1258", value: "Orange Beach" },
  { key: "1259", value: "Oranjestad (Aruba)" },
  { key: "1260", value: "Oranjestad (Sint Eustatius)" },
  { key: "1261", value: "Orem" },
  { key: "1262", value: "Oristano" },
  { key: "1263", value: "Orlando" },
  { key: "1264", value: "Orléans" },
  { key: "1265", value: "Ortisei" },
  { key: "1266", value: "Osaka" },
  { key: "1267", value: "Oshawa" },
  { key: "1268", value: "Oshkosh" },
  { key: "1269", value: "Oslo" },
  { key: "1270", value: "Osnabrück" },
  { key: "1271", value: "Ostrava" },
  { key: "1272", value: "Ottawa" },
  { key: "1273", value: "Ouagadougou" },
  { key: "1274", value: "Oulu" },
  { key: "1275", value: "Ourense" },
  { key: "1276", value: "Overland Park" },
  { key: "1277", value: "Oviedo" },
  { key: "1278", value: "Owensboro" },
  { key: "1279", value: "Oxford" },
  { key: "1280", value: "Oxnard" },
  { key: "1281", value: "Pacific Grove" },
  { key: "1282", value: "Padang" },
  { key: "1283", value: "Paderborn" },
  { key: "1284", value: "Padova" },
  { key: "1285", value: "Pago Pago" },
  { key: "1286", value: "Palanga" },
  { key: "1287", value: "Palavas-les-Flots" },
  { key: "1288", value: "Palembang" },
  { key: "1289", value: "Palermo" },
  { key: "1290", value: "Palikir" },
  { key: "1291", value: "Palm Bay" },
  { key: "1292", value: "Palm Beach" },
  { key: "1293", value: "Palm Springs" },
  { key: "1294", value: "Palma de Mallorca" },
  { key: "1295", value: "Palma Nova" },
  { key: "1296", value: "Palmetto" },
  { key: "1297", value: "Palo Alto" },
  { key: "1298", value: "Pamplona" },
  { key: "1299", value: "Panama City (U.S.)" },
  { key: "1300", value: "Panama City (Panama)" },
  { key: "1301", value: "Paphos" },
  { key: "1302", value: "Paradiski" },
  { key: "1303", value: "Paralia" },
  { key: "1304", value: "Paramaribo" },
  { key: "1305", value: "Parikia" },
  { key: "1306", value: "Paris" },
  { key: "1307", value: "Parkersburg" },
  { key: "1308", value: "Parksville" },
  { key: "1309", value: "Parma" },
  { key: "1310", value: "Pärnu" },
  { key: "1311", value: "Pasadena" },
  { key: "1312", value: "Passo del Tonale" },
  { key: "1313", value: "Passo Rolle" },
  { key: "1314", value: "Paterson" },
  { key: "1315", value: "Patras" },
  { key: "1316", value: "Pattaya" },
  { key: "1317", value: "Pau" },
  { key: "1318", value: "Pavia" },
  { key: "1319", value: "Peel" },
  { key: "1320", value: "Peguera" },
  { key: "1321", value: "Pembroke Pines" },
  { key: "1322", value: "Peniscola" },
  { key: "1323", value: "Pensacola" },
  { key: "1324", value: "Peoria" },
  { key: "1325", value: "Perast" },
  { key: "1326", value: "Perdido Key" },
  { key: "1327", value: "Périgueux" },
  { key: "1328", value: "Perpignan" },
  { key: "1329", value: "Perros-Guirec" },
  { key: "1330", value: "Perth (Australia)" },
  { key: "1331", value: "Perth (UK)" },
  { key: "1332", value: "Perugia" },
  { key: "1333", value: "Pesaro" },
  { key: "1334", value: "Pescara" },
  { key: "1335", value: "Pescasseroli" },
  { key: "1336", value: "Petah Tikva" },
  { key: "1337", value: "Peterborough" },
  { key: "1338", value: "Petra" },
  { key: "1339", value: "Petrovac" },
  { key: "1340", value: "Pforzheim" },
  { key: "1341", value: "Phang Nga" },
  { key: "1342", value: "Phetchabun" },
  { key: "1343", value: "Philadelphia" },
  { key: "1344", value: "Philipsburg" },
  { key: "1345", value: "Phoenix" },
  { key: "1346", value: "Phuket City" },
  { key: "1347", value: "Piacenza" },
  { key: "1348", value: "Pierre" },
  { key: "1349", value: "Pine Bluff" },
  { key: "1350", value: "Piraeus" },
  { key: "1351", value: "Piran" },
  { key: "1352", value: "Pisa" },
  { key: "1353", value: "Pistoia" },
  { key: "1354", value: "Pittsburgh" },
  { key: "1355", value: "Placencia" },
  { key: "1356", value: "Plano" },
  { key: "1357", value: "Playa Blanca" },
  { key: "1358", value: "Playa de las Américas" },
  { key: "1359", value: "Playa del Carmen" },
  { key: "1360", value: "Pleasure Point" },
  { key: "1361", value: "Plovdiv" },
  { key: "1362", value: "Plymouth" },
  { key: "1363", value: "Plzeň" },
  { key: "1364", value: "Podgorica" },
  { key: "1365", value: "Pointe-à-Pitre" },
  { key: "1366", value: "Poitiers" },
  { key: "1367", value: "Pollença" },
  { key: "1368", value: "Pompano Beach" },
  { key: "1369", value: "Pontevedra" },
  { key: "1370", value: "Pordenone" },
  { key: "1371", value: "Poreč" },
  { key: "1372", value: "Porlamar" },
  { key: "1373", value: "Port Alberni" },
  { key: "1374", value: "Port Angeles" },
  { key: "1375", value: "Port Charlotte" },
  { key: "1376", value: "Port d'Andratx" },
  { key: "1377", value: "Port Louis" },
  { key: "1378", value: "Port Moresby" },
  { key: "1379", value: "Port of Spain" },
  { key: "1380", value: "Port St. Lucie" },
  { key: "1381", value: "Port Townsend" },
  { key: "1382", value: "Port Vila" },
  { key: "1383", value: "Port-au-Prince" },
  { key: "1384", value: "Portimão" },
  { key: "1385", value: "Portland (Oregon)" },
  { key: "1386", value: "Portland (Maine)" },
  { key: "1387", value: "Porto" },
  { key: "1388", value: "Porto Cervo" },
  { key: "1389", value: "Porto Cristo" },
  { key: "1390", value: "Porto Torres" },
  { key: "1391", value: "Portocolom" },
  { key: "1392", value: "Portoferraio" },
  { key: "1393", value: "Portofino" },
  { key: "1394", value: "Porto-Novo" },
  { key: "1395", value: "Portorož" },
  { key: "1396", value: "Porto-Vecchio" },
  { key: "1397", value: "Portsmouth (UK)" },
  { key: "1398", value: "Portsmouth (U.S.)" },
  { key: "1399", value: "Positano" },
  { key: "1400", value: "Potenza" },
  { key: "1401", value: "Potsdam" },
  { key: "1402", value: "Poznan" },
  { key: "1403", value: "Pozzuoli" },
  { key: "1404", value: "Prague" },
  { key: "1405", value: "Praia" },
  { key: "1406", value: "Praia da Rocha" },
  { key: "1407", value: "Prato" },
  { key: "1408", value: "Prescott" },
  { key: "1409", value: "Preston" },
  { key: "1410", value: "Pretoria" },
  { key: "1411", value: "Prince Albert" },
  { key: "1412", value: "Prince George" },
  { key: "1413", value: "Prince Rupert" },
  { key: "1414", value: "Pristina" },
  { key: "1415", value: "Propriano" },
  { key: "1416", value: "Protaras" },
  { key: "1417", value: "Providence" },
  { key: "1418", value: "Provincetown" },
  { key: "1419", value: "Provo" },
  { key: "1420", value: "Pueblo" },
  { key: "1421", value: "Puerto Baquerizo Moreno" },
  { key: "1422", value: "Puerto Cortés" },
  { key: "1423", value: "Puerto de la Cruz" },
  { key: "1424", value: "Puerto la Cruz" },
  { key: "1425", value: "Puerto Plata" },
  { key: "1426", value: "Puerto Princesa" },
  { key: "1427", value: "Puerto Rico de Gran Canaria" },
  { key: "1428", value: "Puerto Vallarta" },
  { key: "1429", value: "Pula" },
  { key: "1430", value: "Punta Arenas" },
  { key: "1431", value: "Punta Cana" },
  { key: "1432", value: "Punta del Este" },
  { key: "1433", value: "Punta Gorda" },
  { key: "1434", value: "Pyeongchang" },
  { key: "1435", value: "Pyongyang" },
  { key: "1436", value: "Quarteira" },
  { key: "1437", value: "Quebec" },
  { key: "1438", value: "Quetzaltenango" },
  { key: "1439", value: "Quezon City" },
  { key: "1440", value: "Quimper" },
  { key: "1441", value: "Quito" },
  { key: "1442", value: "Rabat" },
  { key: "1443", value: "Racine" },
  { key: "1444", value: "Ragusa" },
  { key: "1445", value: "Railay Beach" },
  { key: "1446", value: "Raleigh" },
  { key: "1447", value: "Ramallah" },
  { key: "1448", value: "Ramsey" },
  { key: "1449", value: "Rancho Cucamonga" },
  { key: "1450", value: "Randers" },
  { key: "1451", value: "Rapallo" },
  { key: "1452", value: "Rapid City" },
  { key: "1453", value: "Ras al-Khaimah" },
  { key: "1454", value: "Ras Sedr" },
  { key: "1455", value: "Ratingen" },
  { key: "1456", value: "Ravello" },
  { key: "1457", value: "Ravenna" },
  { key: "1458", value: "Rayong" },
  { key: "1459", value: "Reading" },
  { key: "1460", value: "Red Deer" },
  { key: "1461", value: "Redding" },
  { key: "1462", value: "Redondo Beach" },
  { key: "1463", value: "Regensburg" },
  { key: "1464", value: "Reggio Calabria" },
  { key: "1465", value: "Reggio Emilia" },
  { key: "1466", value: "Regina" },
  { key: "1467", value: "Rehovot" },
  { key: "1468", value: "Reims" },
  { key: "1469", value: "Rennes" },
  { key: "1470", value: "Reno" },
  { key: "1471", value: "Rethymno" },
  { key: "1472", value: "Reus" },
  { key: "1473", value: "Reutlingen" },
  { key: "1474", value: "Reykjavik" },
  { key: "1475", value: "Rhodes" },
  { key: "1476", value: "Richmond" },
  { key: "1477", value: "Rieti" },
  { key: "1478", value: "Riga" },
  { key: "1479", value: "Rijeka" },
  { key: "1480", value: "Rimini" },
  { key: "1481", value: "Rio de Janeiro" },
  { key: "1482", value: "Riomaggiore" },
  { key: "1483", value: "Rishon LeZion" },
  { key: "1484", value: "Rivas" },
  { key: "1485", value: "Riverside" },
  { key: "1486", value: "Riviera Maya" },
  { key: "1487", value: "Road Town" },
  { key: "1488", value: "Roanoke" },
  { key: "1489", value: "Rocamadour" },
  { key: "1490", value: "Rochester (Minnesota)" },
  { key: "1491", value: "Rochester (New York)" },
  { key: "1492", value: "Rock Hill" },
  { key: "1493", value: "Rockford" },
  { key: "1494", value: "Rockville" },
  { key: "1495", value: "Rodez" },
  { key: "1496", value: "Rogers" },
  { key: "1497", value: "Rome" },
  { key: "1498", value: "Ronda" },
  { key: "1499", value: "Rosario" },
  { key: "1500", value: "Roseau" },
  { key: "1501", value: "Roskilde" },
  { key: "1502", value: "Rostock" },
  { key: "1503", value: "Roswell" },
  { key: "1504", value: "Rotterdam" },
  { key: "1505", value: "Roubaix" },
  { key: "1506", value: "Rouen" },
  { key: "1507", value: "Rovigo" },
  { key: "1508", value: "Rovinj" },
  { key: "1509", value: "Rutland" },
  { key: "1510", value: "Sa Coma" },
  { key: "1511", value: "Sa Pobla" },
  { key: "1512", value: "Saalbach" },
  { key: "1513", value: "Saarbrücken" },
  { key: "1514", value: "Saas-Fee" },
  { key: "1515", value: "Sacramento" },
  { key: "1516", value: "Safaga" },
  { key: "1517", value: "Saguenay" },
  { key: "1518", value: "Saint John" },
  { key: "1519", value: "Saint Paul" },
  { key: "1520", value: "Saint Petersburg" },
  { key: "1521", value: "Saint-Brieuc" },
  { key: "1522", value: "Sainte-Maxime" },
  { key: "1523", value: "Saintes-Maries-de-la-Mer" },
  { key: "1524", value: "Saint-Étienne" },
  { key: "1525", value: "Saint-Jean-Cap-Ferrat" },
  { key: "1526", value: "Saint-Jean-sur-Richelieu" },
  { key: "1527", value: "Saint-Jérôme" },
  { key: "1528", value: "Saint-Laurent-du-Maroni" },
  { key: "1529", value: "Saint-Malo" },
  { key: "1530", value: "Saint-Tropez" },
  { key: "1531", value: "Salamanca" },
  { key: "1532", value: "Salem (Oregon)" },
  { key: "1533", value: "Salem (Massachusetts)" },
  { key: "1534", value: "Salerno" },
  { key: "1535", value: "Salinas" },
  { key: "1536", value: "Salisbury" },
  { key: "1537", value: "Salou" },
  { key: "1538", value: "Salt Lake City" },
  { key: "1539", value: "Salta" },
  { key: "1540", value: "Salvador" },
  { key: "1541", value: "Salzburg" },
  { key: "1542", value: "Samaná" },
  { key: "1543", value: "San Angelo" },
  { key: "1544", value: "San Antonio" },
  { key: "1545", value: "San Bernardino" },
  { key: "1546", value: "San Clemente" },
  { key: "1547", value: "San Cristóbal" },
  { key: "1548", value: "San Diego" },
  { key: "1549", value: "San Fernando" },
  { key: "1550", value: "San Francisco" },
  { key: "1551", value: "San José (Costa Rica)" },
  { key: "1552", value: "San Jose (U.S.)" },
  { key: "1553", value: "San Juan" },
  { key: "1554", value: "San Juan del Sur" },
  { key: "1555", value: "San Lorenzo" },
  { key: "1556", value: "San Luis Obispo" },
  { key: "1557", value: "San Marino" },
  { key: "1558", value: "San Mateo" },
  { key: "1559", value: "San Miguel" },
  { key: "1560", value: "San Pedro" },
  { key: "1561", value: "San Pedro de Atacama" },
  { key: "1562", value: "San Pedro Sula" },
  { key: "1563", value: "San Rafael" },
  { key: "1564", value: "San Salvador" },
  { key: "1565", value: "San Sebastián" },
  { key: "1566", value: "Sanaa" },
  { key: "1567", value: "Sanford" },
  { key: "1568", value: "Sanibel Island" },
  { key: "1569", value: "Sanremo" },
  { key: "1570", value: "Sant Antoni de Portmany" },
  { key: "1571", value: "Santa Ana (U.S.)" },
  { key: "1572", value: "Santa Ana (El Salvador)" },
  { key: "1573", value: "Santa Barbara" },
  { key: "1574", value: "Santa Clara" },
  { key: "1575", value: "Santa Clarita" },
  { key: "1576", value: "Santa Cruz" },
  { key: "1577", value: "Santa Cruz de la Sierra" },
  { key: "1578", value: "Santa Cruz de Tenerife" },
  { key: "1579", value: "Santa Eulària des Riu" },
  { key: "1580", value: "Santa Fe" },
  { key: "1581", value: "Santa Lucía" },
  { key: "1582", value: "Santa Margherita Ligure" },
  { key: "1583", value: "Santa Maria (Cape Verde)" },
  { key: "1584", value: "Santa Maria (U.S.)" },
  { key: "1585", value: "Santa Monica" },
  { key: "1586", value: "Santa Pola" },
  { key: "1587", value: "Santa Ponsa" },
  { key: "1588", value: "Santa Rosa" },
  { key: "1589", value: "Santa Tecla" },
  { key: "1590", value: "Santander" },
  { key: "1591", value: "Santanyí" },
  { key: "1592", value: "Santiago (Chile)" },
  { key: "1593", value: "Santiago (Dominican Rep.)" },
  { key: "1594", value: "Santiago de Compostela" },
  { key: "1595", value: "Santo Domingo" },
  { key: "1596", value: "Sanur" },
  { key: "1597", value: "Sao Paulo" },
  { key: "1598", value: "São Tomé" },
  { key: "1599", value: "Sapporo" },
  { key: "1600", value: "Sarajevo" },
  { key: "1601", value: "Sarasota" },
  { key: "1602", value: "Saratoga Springs" },
  { key: "1603", value: "S'Arenal" },
  { key: "1604", value: "Sariaya" },
  { key: "1605", value: "Sarlat-la-Canéda" },
  { key: "1606", value: "Saskatoon" },
  { key: "1607", value: "Sassari" },
  { key: "1608", value: "Sault Ste. Marie" },
  { key: "1609", value: "Saumur" },
  { key: "1610", value: "Savannah" },
  { key: "1611", value: "Savona" },
  { key: "1612", value: "Savusavu" },
  { key: "1613", value: "Schaffhausen" },
  { key: "1614", value: "Schenectady" },
  { key: "1615", value: "Schladming" },
  { key: "1616", value: "Scottsdale" },
  { key: "1617", value: "Scranton" },
  { key: "1618", value: "Sea Island" },
  { key: "1619", value: "Sea Isle City" },
  { key: "1620", value: "Seal Beach" },
  { key: "1621", value: "Seaside" },
  { key: "1622", value: "Seattle" },
  { key: "1623", value: "Sedona" },
  { key: "1624", value: "Seefeld" },
  { key: "1625", value: "Segovia" },
  { key: "1626", value: "Semarang" },
  { key: "1627", value: "Seminyak" },
  { key: "1628", value: "Seoul" },
  { key: "1629", value: "Serre Chevalier" },
  { key: "1630", value: "Sète" },
  { key: "1631", value: "Seville" },
  { key: "1632", value: "Shanghai" },
  { key: "1633", value: "Sharjah" },
  { key: "1634", value: "Sharm el-Sheikh" },
  { key: "1635", value: "Sheffield" },
  { key: "1636", value: "Shenzhen" },
  { key: "1637", value: "Sherbrooke" },
  { key: "1638", value: "Shreveport" },
  { key: "1639", value: "Šiauliai" },
  { key: "1640", value: "Šibenik" },
  { key: "1641", value: "Side" },
  { key: "1642", value: "Siegen" },
  { key: "1643", value: "Siena" },
  { key: "1644", value: "Siesta Key" },
  { key: "1645", value: "Sineu" },
  { key: "1646", value: "Singapore" },
  { key: "1647", value: "Singaraja" },
  { key: "1648", value: "Sion" },
  { key: "1649", value: "Sioux City" },
  { key: "1650", value: "Sioux Falls" },
  { key: "1651", value: "Sitges" },
  { key: "1652", value: "Skiathos" },
  { key: "1653", value: "Skopje" },
  { key: "1654", value: "Sofia" },
  { key: "1655", value: "Sölden" },
  { key: "1656", value: "Söll" },
  { key: "1657", value: "Soller" },
  { key: "1658", value: "Solothurn" },
  { key: "1659", value: "Sondrio" },
  { key: "1660", value: "Sopot" },
  { key: "1661", value: "Sorocaba" },
  { key: "1662", value: "Sorrento" },
  { key: "1663", value: "South Bend" },
  { key: "1664", value: "Southampton" },
  { key: "1665", value: "Split" },
  { key: "1666", value: "Spokane" },
  { key: "1667", value: "Springdale" },
  { key: "1668", value: "Springfield (Illinois)" },
  { key: "1669", value: "Springfield (Massachusetts)" },
  { key: "1670", value: "Springfield (Missouri)" },
  { key: "1671", value: "Springfield (Oregon)" },
  { key: "1672", value: "St Albans" },
  { key: "1673", value: "St George's (Bermuda)" },
  { key: "1674", value: "St Pete Beach" },
  { key: "1675", value: "St. Albans" },
  { key: "1676", value: "St. Anton" },
  { key: "1677", value: "St. Augustine" },
  { key: "1678", value: "St. Catharines" },
  { key: "1679", value: "St. Cloud" },
  { key: "1680", value: "St. Gallen" },
  { key: "1681", value: "St. George" },
  { key: "1682", value: "St. George Island" },
  { key: "1683", value: "St. George's (Grenada)" },
  { key: "1684", value: "St. John's (Antigua and Barbuda)" },
  { key: "1685", value: "St. John's (Canada)" },
  { key: "1686", value: "St. Louis" },
  { key: "1687", value: "St. Moritz" },
  { key: "1688", value: "St. Petersburg (U.S.)" },
  { key: "1689", value: "St. Simons Island" },
  { key: "1690", value: "Stamford" },
  { key: "1691", value: "Stanley" },
  { key: "1692", value: "Stavanger" },
  { key: "1693", value: "Steinbach" },
  { key: "1694", value: "Stillwater" },
  { key: "1695", value: "Stirling" },
  { key: "1696", value: "Stock Island" },
  { key: "1697", value: "Stockholm" },
  { key: "1698", value: "Stockton" },
  { key: "1699", value: "Stoke-on-Trent" },
  { key: "1700", value: "Stone Harbor" },
  { key: "1701", value: "Strasbourg" },
  { key: "1702", value: "Stuttgart" },
  { key: "1703", value: "Sucre" },
  { key: "1704", value: "Sudbury" },
  { key: "1705", value: "Suez" },
  { key: "1706", value: "Sukhothai" },
  { key: "1707", value: "Sukhumi" },
  { key: "1708", value: "Summerside" },
  { key: "1709", value: "Sumter" },
  { key: "1710", value: "Sunderland" },
  { key: "1711", value: "Sunnyvale" },
  { key: "1712", value: "Sunshine Coast" },
  { key: "1713", value: "Superior" },
  { key: "1714", value: "Surabaya" },
  { key: "1715", value: "Surrey" },
  { key: "1716", value: "Suva" },
  { key: "1717", value: "Sveti Stefan" },
  { key: "1718", value: "Swansea" },
  { key: "1719", value: "Sydney (Australia)" },
  { key: "1720", value: "Sydney (Canada)" },
  { key: "1721", value: "Syracuse (Italy)" },
  { key: "1722", value: "Syracuse (U.S.)" },
  { key: "1723", value: "Szczecin" },
  { key: "1724", value: "Taba" },
  { key: "1725", value: "Tacloban" },
  { key: "1726", value: "Tacoma" },
  { key: "1727", value: "Tagbilaran" },
  { key: "1728", value: "Taipei" },
  { key: "1729", value: "Tallahassee" },
  { key: "1730", value: "Tallinn" },
  { key: "1731", value: "Tampa" },
  { key: "1732", value: "Tampere" },
  { key: "1733", value: "Tamworth" },
  { key: "1734", value: "Tangier" },
  { key: "1735", value: "Taormina" },
  { key: "1736", value: "Taranto" },
  { key: "1737", value: "Tarifa" },
  { key: "1738", value: "Tarragona" },
  { key: "1739", value: "Tartu" },
  { key: "1740", value: "Tashkent" },
  { key: "1741", value: "Tauplitz" },
  { key: "1742", value: "Tauranga" },
  { key: "1743", value: "Tavira" },
  { key: "1744", value: "Tbilisi" },
  { key: "1745", value: "Tegucigalpa" },
  { key: "1746", value: "Tel Aviv" },
  { key: "1747", value: "Temecula" },
  { key: "1748", value: "Tempe" },
  { key: "1749", value: "Teramo" },
  { key: "1750", value: "Ternate" },
  { key: "1751", value: "Terni" },
  { key: "1752", value: "Texarkana AR" },
  { key: "1753", value: "Texarkana TX" },
  { key: "1754", value: "The Bottom" },
  { key: "1755", value: "The Hague" },
  { key: "1756", value: "The Valley" },
  { key: "1757", value: "The Wildwoods" },
  { key: "1758", value: "The Woodlands" },
  { key: "1759", value: "Thessaloniki" },
  { key: "1760", value: "Thimphu" },
  { key: "1761", value: "Thunder Bay" },
  { key: "1762", value: "Tignes" },
  { key: "1763", value: "Tijuana" },
  { key: "1764", value: "Tilburg" },
  { key: "1765", value: "Timmins" },
  { key: "1766", value: "Tinos" },
  { key: "1767", value: "Tirana" },
  { key: "1768", value: "Tivat" },
  { key: "1769", value: "Tivoli" },
  { key: "1770", value: "Tokyo" },
  { key: "1771", value: "Toledo (Spain)" },
  { key: "1772", value: "Toledo (U.S.)" },
  { key: "1773", value: "Tooele" },
  { key: "1774", value: "Toowoomba" },
  { key: "1775", value: "Topeka" },
  { key: "1776", value: "Toronto" },
  { key: "1777", value: "Torre del Greco" },
  { key: "1778", value: "Torre del Mar" },
  { key: "1779", value: "Torremolinos" },
  { key: "1780", value: "Torrevieja" },
  { key: "1781", value: "Tórshavn" },
  { key: "1782", value: "Toruń" },
  { key: "1783", value: "Tossa de Mar" },
  { key: "1784", value: "Toulon" },
  { key: "1785", value: "Toulouse" },
  { key: "1786", value: "Tours" },
  { key: "1787", value: "Townsville" },
  { key: "1788", value: "Trani" },
  { key: "1789", value: "Trapani" },
  { key: "1790", value: "Treasure Island" },
  { key: "1791", value: "Trento" },
  { key: "1792", value: "Trenton" },
  { key: "1793", value: "Treviso" },
  { key: "1794", value: "Trier" },
  { key: "1795", value: "Trieste" },
  { key: "1796", value: "Tripoli" },
  { key: "1797", value: "Trogir" },
  { key: "1798", value: "Trois-Rivières" },
  { key: "1799", value: "Tromsø" },
  { key: "1800", value: "Trondheim" },
  { key: "1801", value: "Trouville-sur-Mer" },
  { key: "1802", value: "Troy" },
  { key: "1803", value: "Troyes" },
  { key: "1804", value: "Trujillo" },
  { key: "1805", value: "Tucson" },
  { key: "1806", value: "Tui" },
  { key: "1807", value: "Tulsa" },
  { key: "1808", value: "Tulum" },
  { key: "1809", value: "Turin" },
  { key: "1810", value: "Turku" },
  { key: "1811", value: "Tuscaloosa" },
  { key: "1812", value: "Twin Falls" },
  { key: "1813", value: "Two Harbors" },
  { key: "1814", value: "Tybee Island" },
  { key: "1815", value: "Tyler" },
  { key: "1816", value: "Ubud" },
  { key: "1817", value: "Udine" },
  { key: "1818", value: "Udon Thani" },
  { key: "1819", value: "Ukiah" },
  { key: "1820", value: "Ulaanbaatar" },
  { key: "1821", value: "Ulcinj" },
  { key: "1822", value: "Ulm" },
  { key: "1823", value: "Umag" },
  { key: "1824", value: "Uppsala" },
  { key: "1825", value: "Urbino" },
  { key: "1826", value: "Urubamba" },
  { key: "1827", value: "Ushuaia" },
  { key: "1828", value: "Utica" },
  { key: "1829", value: "Utrecht" },
  { key: "1830", value: "Vaduz" },
  { key: "1831", value: "Val d’Isère" },
  { key: "1832", value: "Val di Fassa" },
  { key: "1833", value: "Val Gardena" },
  { key: "1834", value: "Val Thorens" },
  { key: "1835", value: "Valence" },
  { key: "1836", value: "Valencia (Spain)" },
  { key: "1837", value: "Valencia (Venezuela)" },
  { key: "1838", value: "Valladolid" },
  { key: "1839", value: "Valldemossa" },
  { key: "1840", value: "Valle Isarco" },
  { key: "1841", value: "Valletta" },
  { key: "1842", value: "Valparaíso" },
  { key: "1843", value: "Vancouver (Canada)" },
  { key: "1844", value: "Vancouver (U.S.)" },
  { key: "1845", value: "Varazze" },
  { key: "1846", value: "Varese" },
  { key: "1847", value: "Varna" },
  { key: "1848", value: "Vaughan" },
  { key: "1849", value: "Vejle" },
  { key: "1850", value: "Venice (Italy)" },
  { key: "1851", value: "Venice (U.S.)" },
  { key: "1852", value: "Ventimiglia" },
  { key: "1853", value: "Ventspils" },
  { key: "1854", value: "Ventura" },
  { key: "1855", value: "Verbania" },
  { key: "1856", value: "Verbier" },
  { key: "1857", value: "Vercelli" },
  { key: "1858", value: "Vero Beach" },
  { key: "1859", value: "Verona" },
  { key: "1860", value: "Versailles" },
  { key: "1861", value: "Vevey" },
  { key: "1862", value: "Viareggio" },
  { key: "1863", value: "Vibo Valentia" },
  { key: "1864", value: "Viborg" },
  { key: "1865", value: "Vicenza" },
  { key: "1866", value: "Vichy" },
  { key: "1867", value: "Victoria (Canada)" },
  { key: "1868", value: "Victoria (Seychelles)" },
  { key: "1869", value: "Victorville" },
  { key: "1870", value: "Vienna" },
  { key: "1871", value: "Vigan" },
  { key: "1872", value: "Vigo" },
  { key: "1873", value: "Vilamoura" },
  { key: "1874", value: "Villach" },
  { key: "1875", value: "Villefranche-sur-Mer" },
  { key: "1876", value: "Vilnius" },
  { key: "1877", value: "Viña del Mar" },
  { key: "1878", value: "Virginia Beach" },
  { key: "1879", value: "Visalia" },
  { key: "1880", value: "Viterbo" },
  { key: "1881", value: "Vitoria-Gasteiz" },
  { key: "1882", value: "Volos" },
  { key: "1883", value: "Vrsar" },
  { key: "1884", value: "Waco" },
  { key: "1885", value: "Wakefield" },
  { key: "1886", value: "Warsaw" },
  { key: "1887", value: "Warth" },
  { key: "1888", value: "Washington D.C." },
  { key: "1889", value: "Waterford" },
  { key: "1890", value: "Watertown" },
  { key: "1891", value: "Watsonville" },
  { key: "1892", value: "Waukegan" },
  { key: "1893", value: "Waukesha" },
  { key: "1894", value: "Wellington (New Zealand)" },
  { key: "1895", value: "Wellington (U.S.)" },
  { key: "1896", value: "Wengen" },
  { key: "1897", value: "Weno" },
  { key: "1898", value: "West Lafayette" },
  { key: "1899", value: "West Palm Beach" },
  { key: "1900", value: "Westendorf" },
  { key: "1901", value: "Westminster" },
  { key: "1902", value: "Weston" },
  { key: "1903", value: "Wheeling" },
  { key: "1904", value: "White Plains" },
  { key: "1905", value: "Whitehorse" },
  { key: "1906", value: "Wichita" },
  { key: "1907", value: "Wichita Falls" },
  { key: "1908", value: "Wiesbaden" },
  { key: "1909", value: "Wildwood" },
  { key: "1910", value: "Wilkes-Barre" },
  { key: "1911", value: "Willemstad" },
  { key: "1912", value: "Williams" },
  { key: "1913", value: "Wilmington (Delaware)" },
  { key: "1914", value: "Wilmington (North Carolina)" },
  { key: "1915", value: "Winchester" },
  { key: "1916", value: "Windhoek" },
  { key: "1917", value: "Windsor" },
  { key: "1918", value: "Winnipeg" },
  { key: "1919", value: "Winslow" },
  { key: "1920", value: "Winston–Salem" },
  { key: "1921", value: "Winterthur" },
  { key: "1922", value: "Wolfsburg" },
  { key: "1923", value: "Wollongong" },
  { key: "1924", value: "Wolverhampton" },
  { key: "1925", value: "Woodburn" },
  { key: "1926", value: "Worcester (UK)" },
  { key: "1927", value: "Worcester (U.S.)" },
  { key: "1928", value: "Worthing" },
  { key: "1929", value: "Wroclaw" },
  { key: "1930", value: "Wuppertal" },
  { key: "1931", value: "Würzburg" },
  { key: "1932", value: "Yakima" },
  { key: "1933", value: "Yamoussoukro" },
  { key: "1934", value: "Yaoundé" },
  { key: "1935", value: "Yaren" },
  { key: "1936", value: "Yellowknife" },
  { key: "1937", value: "Yerevan" },
  { key: "1938", value: "Yogyakarta" },
  { key: "1939", value: "Yokohama" },
  { key: "1940", value: "Yonkers" },
  { key: "1941", value: "York (UK)" },
  { key: "1942", value: "York (U.S.)" },
  { key: "1943", value: "Youngstown" },
  { key: "1944", value: "Yuma" },
  { key: "1945", value: "Zadar" },
  { key: "1946", value: "Zagreb" },
  { key: "1947", value: "Zakopane" },
  { key: "1948", value: "Zamboanga City" },
  { key: "1949", value: "Zanzibar" },
  { key: "1950", value: "Zaragoza" },
  { key: "1951", value: "Zell am See" },
  { key: "1952", value: "Zell am Ziller" },
  { key: "1953", value: "Zermatt" },
  { key: "1954", value: "Zug" },
  { key: "1955", value: "Zurich" },
  { key: "1956", value: "Zwickau" },
  { key: "1957", value: "Zwolle" },
];
